name: pr-danger

on:
  pull_request:
    branches-ignore:
      - 'master'
      - 'sandbox'

jobs:
  danger:
    name: Danger
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4 
    - name: cache bundle
      uses: actions/cache@v2.1.6
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: setup bundle
      run: |
        gem install bundler
        bundle install
    - name: run danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bundle exec danger
